apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:{{- range .Values.domains }}
  - host: {{ $.Values.subdomain }}.{{ . }}
    http:
      paths:
      - backend:
          service:
            name: {{ $.Release.Name }}
            port:
              name: http
        path: /
        pathType: Prefix
{{- end }}
  tls:
  - hosts:
    - arrakis.jskw.dev
    - '*.arrakis.jskw.dev'
    secretName: wild-arrakis
  - hosts:
    - jskw.dev
    - '*.jskw.dev'
    secretName: wild-jskw-dev
