name: poker-chart
apiVersion: v2
version: "0.0.1"
icon: https://kwlug.org/themes/kwlug_theme/logo.svg
dependencies:
  - name: postgresql
    version: ~11.1.25
    repository: https://charts.bitnami.com/bitnami
    alias: db